networks:
  sonarqube:
    driver: bridge
  common-net:
    external: true

services:

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    hostname: sonarqube
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - TZ=Asia/Yekaterinburg
    networks:
      - sonarqube
      - common-net
    ports:
      - "9001:9092"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  sonarqube_db:
    image: postgres:latest
    container_name: sonarqube_db
    hostname: sonarqube_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Yekaterinburg
    networks:
      - sonarqube
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
