networks:
  postgresql:
    driver: bridge

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgresql
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Yekaterinburg
    networks:
      - postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G