networks:
  n8n:
    driver: bridge
  common-net:
    external: true

services:
  n8n_db:
    image: postgres:16
    container_name: n8n_db
    hostname: n8n_db
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Yekaterinburg
    volumes:
       - ./n8n_db:/var/lib/postgresql/data
    networks:
      - n8n
      - common-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n -d n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_PATH=/
      - WEBHOOK_URL=http://n8n.dev.lan
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./storage/:/home/node/.n8n
    networks:
      - n8n
      - common-net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G