networks:
  rabbitmq:
    driver: bridge
  common-net:
    external: true

services:

  rabbitmq:
    image: rabbitmq:4.2-rc-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - TZ=Asia/Yekaterinburg
    networks:
      - rabbitmq
      - common-net
    ports:
      - "5672:5672"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G