networks:
  gitlab:
    driver: bridge
  common-net:
    external: true

services:

  gitlab:
    image: "gitlab/gitlab-ee:latest"
    container_name: gitlab
    hostname: "gitlab.local"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://0.0.0.0:8929"
        gitlab_rails["gitlab_shell_ssh_port"] = 2224
      TZ: Asia/Yekaterinburg
    networks:
      - gitlab
      - common-net
    ports:
      - "2224:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: "1024m"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G
