networks:
  nginx:
    driver: bridge
  common-net:
    external: true

services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d/
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/error_pages.conf:/etc/nginx/error_pages.conf
      - ./nginx/conf/ssl:/etc/nginx/ssl/
      - ./nginx/www/error_pages:/usr/share/nginx/html/error_pages
      - ./nginx/www:/usr/share/nginx/html/
    networks:
      - nginx
      - common-net
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
