networks:
  redis:
    driver: bridge

services:

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    environment:
      - TZ=Asia/Yekaterinburg
    networks:
      - redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 500M